* Monday Keynote "Beware of red flags on the net"

Rick Falkvinger - Founder of the first Piraet Party

About two thirds of audience have heard of the Swedish Pirate party.

How many people have heard of any other swedish partys? Not many..

Internet, Copying and Sharing, Civil Liberties. Call us pirates to
shame us, but we stand tall. Various seats across EU, germany, local
etc.

Who were the pioneers in digital photography? Polaroid and Kodak. 

Polaroid bankrupt in 2001. Kodak this year.

Despite fact that they were pioneers, they felt this new tech was
going to cannabalise exisitng products. Patented, didnt bring to
market, didnt capitilise on it.

Kodak invented digital camera in 1976!!! 

Stock graph of kodak and canon.

Most incumbent companies dont ignoire new tech, they try to kill it.

"Just a protest party"

Disagreeing with the status quo is dissent by definition.

40 years ago you had the greens that protested pollution and regulated
industry.

80 years ago workers movement.

Liberals that protested ovearching rights of king and church.

17 yo of today have for first time changed since 17. The values of 17
year olds of what discussion and politics will look like in next few
decades.

No longer 'sustainability', free speech and open ness. Selling free
speech to highest corporate bidder... 

Mubarak took away the internet ...

What we are demanding is not rocket science. A letter in the mail 40
years ago - anonymous (you can choose whether you ident yourself),
secret in transit, untracked. Mailman not responsible for the message.

We want our children to have the same rights as our parents
have. Corporates say 'but we cant make money'. You dont get to
dismantle civil liberties.

** Reaction of the incumbents

UK mid 1800s

Industrial revolution, people's lives were changing. Automobile (sort
of) arriving in the street. 

New things scare people. (and horses!).

"Red Flag act" 1865. Any car on streets of UK, should have a crew of
three people: driver, stoker and a person walking in front waving a
red flag.

Max speed 3kmph- but obviously constrained to the walking
speed. Feeding the railroad/stagecoach networks with passengers

People pushing for the red flag act, railroad and stagecoach
networks. Classic technique- 'embrace' new tech but limit its
usefulness. Car was banned from competing.

Just Britain, Gernay got a 20 year head start. Separated
publich/private interetes.

If an industry is obsolete, saving jobs in it counter productive.

More recent - electric car batteries. Bought by GM, patented etc.

** Inofmration is dangerous

So powerful, can unseat prime ministers, etc. 

US + Julian Assange. 

Socilogists divide net into two groups. First group says that it is as
imporant as printing press, other group say better since written word
invented. Greatest equaliser that has beeen invented.

Puts my words on same footing as words of a 9 yo paragyuayen girl who
just got on line in laptops for children sceheme.

Pre printing press, Church was powerful. Catholic church didnt worry
about law being written against it.

Monks copied books by hand.

1453 - printing press.

How will the monks get paid?

all of a sudden, everyone and their brother was allowed to spread
informartion.

Following inventing, laws against printing press + copying ideas
gradually appered.

Kept ramping up the punishment - hanging for copying

Decided they needed somethinge else. So created 'unholy alliance' with
printing press. Monopoly awarded 1557. Called copyright - still
around!

Originally a method of stopping concent.

Throughout history: People in Power use their Power to keep their power!

** News papers

** About every five/ten years, the sky is falling

Copyright Industry's enemies

1905 Self playing piano

200x? Cloud!

Throw tantrusm => get taxpayer monkey

** Crystal ball : Industries repeating red flags

What industries are maybe about to fall next.

Disription slow.

What is going?

*** Postal services

ignored email, degraded into glorified bill carriers.

Still in 2012 getting us to send Xmas cards!

*** News Services

Used to be elite/monipolistic. Small cadre of people oculd decide
truth. Now all bloggers too. "Old Media"

*** Copyright services


** pricacy

Crypto currency "drop kick" the entire bank sysem

** Telco industry.

   Sitll paybing by the minute..
Business models do not add up any longer

** Governments

P2P effectively no cnetral control. Cannot touch p2p.

Going to be a buerocratic nightmare. 

** ALL OF THIS HAS HAPPENED BEFORE

All of this will happen again. (Battlestar gallactica)


